// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/andrewjapar/andrew-cv-app/domain"
	mock "github.com/stretchr/testify/mock"
)

// PodcastRepository is an autogenerated mock type for the PodcastRepository type
type PodcastRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *PodcastRepository) Get() ([]domain.Podcast, error) {
	ret := _m.Called()

	var r0 []domain.Podcast
	if rf, ok := ret.Get(0).(func() []domain.Podcast); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Podcast)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
