// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/andrewjapar/andrew-cv-app/domain"
	mock "github.com/stretchr/testify/mock"
)

// WeddingRepository is an autogenerated mock type for the WeddingRepository type
type WeddingRepository struct {
	mock.Mock
}

// GetByUserID provides a mock function with given fields: id
func (_m *WeddingRepository) GetByUserID(id int64) ([]domain.Wedding, error) {
	ret := _m.Called(id)

	var r0 []domain.Wedding
	if rf, ok := ret.Get(0).(func(int64) []domain.Wedding); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Wedding)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
